version: '3.3'
services:
       web:
           build:
               context: .
               dockerfile: Dockerfile
           container_name: web-kelompok3
           depends_on:
               - db
           volumes:
               - ./:/var/www/html
           ports:
               - 8000:80
       db:
           container_name: kel3db
           image: mysql:8.0
           command: --default-authentication-plugin=mysql_native_password
           restart: always
           environment:
               MYSQL_ROOT_PASSWORD: root
               MYSQL_DATABASE: assignment
               MYSQL_USER: alfa
               MYSQL_PASSWORD: 123170027
           ports:
               - 6036:3306
